

 <script type="text/javascript">
    //  require(['jquery', 'Innovadeltech_Convertopia/js/products']);


     require(['jquery'], function($) {
         // Your JavaScript code here
         $(document).ready(function() {
             var dataLayerObject = '<?=  /* @noEscape */ $block->getRequest()->getFullActionName(); ?>';
             if (dataLayerObject == 'cms_index_index' || dataLayerObject == 'catalog_product_view') {
               
                // require(['Innovadeltech_Convertopia/js/products'], function(products) {
                //          products.renderTileProduct([95,96,97,159,160,161,111,112,113,14,20,19]);
                //      });
               
                // window.CONVERTOPIA.getRecommendation(renderProducts, window.CONVERTOPIA.CONSTANT.RECO_TYPES.USER, {
                //      "user_id": "1234"
                //  });

                //  function renderProducts(productIds) {
                //      var productIdsObject = JSON.parse(productIds);
                //      var recommendedId = productIdsObject.recommended;
                //      require(['Innovadeltech_Convertopia/js/products'], function(products) {
                //          products.renderTileProduct(recommendedId);
                //      });
                //      console.log(recommendedId);
                //      // products.renderTileProduct(recommendedId)

                //  }
             }

         });
     });
 </script>